// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: countgroup.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CountGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CountGroupRequest) Reset() {
	*x = CountGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_countgroup_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountGroupRequest) ProtoMessage() {}

func (x *CountGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_countgroup_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountGroupRequest.ProtoReflect.Descriptor instead.
func (*CountGroupRequest) Descriptor() ([]byte, []int) {
	return file_countgroup_proto_rawDescGZIP(), []int{0}
}

type CountGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *CountGroupResponse) Reset() {
	*x = CountGroupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_countgroup_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountGroupResponse) ProtoMessage() {}

func (x *CountGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_countgroup_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountGroupResponse.ProtoReflect.Descriptor instead.
func (*CountGroupResponse) Descriptor() ([]byte, []int) {
	return file_countgroup_proto_rawDescGZIP(), []int{1}
}

func (x *CountGroupResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_countgroup_proto protoreflect.FileDescriptor

var file_countgroup_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x13, 0x0a, 0x11, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2a,
	0x0a, 0x12, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0x51, 0x0a, 0x0a, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x43, 0x0a, 0x0a, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0a, 0x5a,
	0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_countgroup_proto_rawDescOnce sync.Once
	file_countgroup_proto_rawDescData = file_countgroup_proto_rawDesc
)

func file_countgroup_proto_rawDescGZIP() []byte {
	file_countgroup_proto_rawDescOnce.Do(func() {
		file_countgroup_proto_rawDescData = protoimpl.X.CompressGZIP(file_countgroup_proto_rawDescData)
	})
	return file_countgroup_proto_rawDescData
}

var file_countgroup_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_countgroup_proto_goTypes = []interface{}{
	(*CountGroupRequest)(nil),  // 0: proto.CountGroupRequest
	(*CountGroupResponse)(nil), // 1: proto.CountGroupResponse
}
var file_countgroup_proto_depIdxs = []int32{
	0, // 0: proto.CountGroup.CountGroup:input_type -> proto.CountGroupRequest
	1, // 1: proto.CountGroup.CountGroup:output_type -> proto.CountGroupResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_countgroup_proto_init() }
func file_countgroup_proto_init() {
	if File_countgroup_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_countgroup_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_countgroup_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountGroupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_countgroup_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_countgroup_proto_goTypes,
		DependencyIndexes: file_countgroup_proto_depIdxs,
		MessageInfos:      file_countgroup_proto_msgTypes,
	}.Build()
	File_countgroup_proto = out.File
	file_countgroup_proto_rawDesc = nil
	file_countgroup_proto_goTypes = nil
	file_countgroup_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CountGroupClient is the client API for CountGroup service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CountGroupClient interface {
	CountGroup(ctx context.Context, in *CountGroupRequest, opts ...grpc.CallOption) (*CountGroupResponse, error)
}

type countGroupClient struct {
	cc grpc.ClientConnInterface
}

func NewCountGroupClient(cc grpc.ClientConnInterface) CountGroupClient {
	return &countGroupClient{cc}
}

func (c *countGroupClient) CountGroup(ctx context.Context, in *CountGroupRequest, opts ...grpc.CallOption) (*CountGroupResponse, error) {
	out := new(CountGroupResponse)
	err := c.cc.Invoke(ctx, "/proto.CountGroup/CountGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CountGroupServer is the server API for CountGroup service.
type CountGroupServer interface {
	CountGroup(context.Context, *CountGroupRequest) (*CountGroupResponse, error)
}

// UnimplementedCountGroupServer can be embedded to have forward compatible implementations.
type UnimplementedCountGroupServer struct {
}

func (*UnimplementedCountGroupServer) CountGroup(context.Context, *CountGroupRequest) (*CountGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CountGroup not implemented")
}

func RegisterCountGroupServer(s *grpc.Server, srv CountGroupServer) {
	s.RegisterService(&_CountGroup_serviceDesc, srv)
}

func _CountGroup_CountGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CountGroupServer).CountGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CountGroup/CountGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CountGroupServer).CountGroup(ctx, req.(*CountGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CountGroup_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CountGroup",
	HandlerType: (*CountGroupServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CountGroup",
			Handler:    _CountGroup_CountGroup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "countgroup.proto",
}
