// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: ungroup.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
}

func (x *UnGroupRequest) Reset() {
	*x = UnGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ungroup_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnGroupRequest) ProtoMessage() {}

func (x *UnGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ungroup_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnGroupRequest.ProtoReflect.Descriptor instead.
func (*UnGroupRequest) Descriptor() ([]byte, []int) {
	return file_ungroup_proto_rawDescGZIP(), []int{0}
}

func (x *UnGroupRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type UnGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *UnGroupResponse) Reset() {
	*x = UnGroupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ungroup_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnGroupResponse) ProtoMessage() {}

func (x *UnGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ungroup_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnGroupResponse.ProtoReflect.Descriptor instead.
func (*UnGroupResponse) Descriptor() ([]byte, []int) {
	return file_ungroup_proto_rawDescGZIP(), []int{1}
}

func (x *UnGroupResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

var File_ungroup_proto protoreflect.FileDescriptor

var file_ungroup_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x75, 0x6e, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x26, 0x0a, 0x0e, 0x55, 0x6e, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x22, 0x29,
	0x0a, 0x0f, 0x55, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x45, 0x0a, 0x07, 0x55, 0x6e, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x12, 0x3a, 0x0a, 0x07, 0x55, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12,
	0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55,
	0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ungroup_proto_rawDescOnce sync.Once
	file_ungroup_proto_rawDescData = file_ungroup_proto_rawDesc
)

func file_ungroup_proto_rawDescGZIP() []byte {
	file_ungroup_proto_rawDescOnce.Do(func() {
		file_ungroup_proto_rawDescData = protoimpl.X.CompressGZIP(file_ungroup_proto_rawDescData)
	})
	return file_ungroup_proto_rawDescData
}

var file_ungroup_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ungroup_proto_goTypes = []interface{}{
	(*UnGroupRequest)(nil),  // 0: proto.UnGroupRequest
	(*UnGroupResponse)(nil), // 1: proto.UnGroupResponse
}
var file_ungroup_proto_depIdxs = []int32{
	0, // 0: proto.UnGroup.UnGroup:input_type -> proto.UnGroupRequest
	1, // 1: proto.UnGroup.UnGroup:output_type -> proto.UnGroupResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ungroup_proto_init() }
func file_ungroup_proto_init() {
	if File_ungroup_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ungroup_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ungroup_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnGroupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ungroup_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ungroup_proto_goTypes,
		DependencyIndexes: file_ungroup_proto_depIdxs,
		MessageInfos:      file_ungroup_proto_msgTypes,
	}.Build()
	File_ungroup_proto = out.File
	file_ungroup_proto_rawDesc = nil
	file_ungroup_proto_goTypes = nil
	file_ungroup_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UnGroupClient is the client API for UnGroup service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UnGroupClient interface {
	UnGroup(ctx context.Context, in *UnGroupRequest, opts ...grpc.CallOption) (*UnGroupResponse, error)
}

type unGroupClient struct {
	cc grpc.ClientConnInterface
}

func NewUnGroupClient(cc grpc.ClientConnInterface) UnGroupClient {
	return &unGroupClient{cc}
}

func (c *unGroupClient) UnGroup(ctx context.Context, in *UnGroupRequest, opts ...grpc.CallOption) (*UnGroupResponse, error) {
	out := new(UnGroupResponse)
	err := c.cc.Invoke(ctx, "/proto.UnGroup/UnGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UnGroupServer is the server API for UnGroup service.
type UnGroupServer interface {
	UnGroup(context.Context, *UnGroupRequest) (*UnGroupResponse, error)
}

// UnimplementedUnGroupServer can be embedded to have forward compatible implementations.
type UnimplementedUnGroupServer struct {
}

func (*UnimplementedUnGroupServer) UnGroup(context.Context, *UnGroupRequest) (*UnGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnGroup not implemented")
}

func RegisterUnGroupServer(s *grpc.Server, srv UnGroupServer) {
	s.RegisterService(&_UnGroup_serviceDesc, srv)
}

func _UnGroup_UnGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnGroupServer).UnGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UnGroup/UnGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnGroupServer).UnGroup(ctx, req.(*UnGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UnGroup_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.UnGroup",
	HandlerType: (*UnGroupServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UnGroup",
			Handler:    _UnGroup_UnGroup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ungroup.proto",
}
