// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: uidisonline.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UidIsOnlineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *UidIsOnlineRequest) Reset() {
	*x = UidIsOnlineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uidisonline_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UidIsOnlineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UidIsOnlineRequest) ProtoMessage() {}

func (x *UidIsOnlineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_uidisonline_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UidIsOnlineRequest.ProtoReflect.Descriptor instead.
func (*UidIsOnlineRequest) Descriptor() ([]byte, []int) {
	return file_uidisonline_proto_rawDescGZIP(), []int{0}
}

func (x *UidIsOnlineRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type UidIsOnlineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *UidIsOnlineResponse) Reset() {
	*x = UidIsOnlineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uidisonline_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UidIsOnlineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UidIsOnlineResponse) ProtoMessage() {}

func (x *UidIsOnlineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_uidisonline_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UidIsOnlineResponse.ProtoReflect.Descriptor instead.
func (*UidIsOnlineResponse) Descriptor() ([]byte, []int) {
	return file_uidisonline_proto_rawDescGZIP(), []int{1}
}

func (x *UidIsOnlineResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

var File_uidisonline_proto protoreflect.FileDescriptor

var file_uidisonline_proto_rawDesc = []byte{
	0x0a, 0x11, 0x75, 0x69, 0x64, 0x69, 0x73, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x26, 0x0a, 0x12, 0x55, 0x69,
	0x64, 0x49, 0x73, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x22, 0x2d, 0x0a, 0x13, 0x55, 0x69, 0x64, 0x49, 0x73, 0x4f, 0x6e, 0x6c, 0x69, 0x6e,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x32, 0x55, 0x0a, 0x0b, 0x55, 0x69, 0x64, 0x49, 0x73, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65,
	0x12, 0x46, 0x0a, 0x0b, 0x55, 0x69, 0x64, 0x49, 0x73, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x12,
	0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x69, 0x64, 0x49, 0x73, 0x4f, 0x6e, 0x6c,
	0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x55, 0x69, 0x64, 0x49, 0x73, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_uidisonline_proto_rawDescOnce sync.Once
	file_uidisonline_proto_rawDescData = file_uidisonline_proto_rawDesc
)

func file_uidisonline_proto_rawDescGZIP() []byte {
	file_uidisonline_proto_rawDescOnce.Do(func() {
		file_uidisonline_proto_rawDescData = protoimpl.X.CompressGZIP(file_uidisonline_proto_rawDescData)
	})
	return file_uidisonline_proto_rawDescData
}

var file_uidisonline_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_uidisonline_proto_goTypes = []interface{}{
	(*UidIsOnlineRequest)(nil),  // 0: proto.UidIsOnlineRequest
	(*UidIsOnlineResponse)(nil), // 1: proto.UidIsOnlineResponse
}
var file_uidisonline_proto_depIdxs = []int32{
	0, // 0: proto.UidIsOnline.UidIsOnline:input_type -> proto.UidIsOnlineRequest
	1, // 1: proto.UidIsOnline.UidIsOnline:output_type -> proto.UidIsOnlineResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_uidisonline_proto_init() }
func file_uidisonline_proto_init() {
	if File_uidisonline_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_uidisonline_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UidIsOnlineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uidisonline_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UidIsOnlineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_uidisonline_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_uidisonline_proto_goTypes,
		DependencyIndexes: file_uidisonline_proto_depIdxs,
		MessageInfos:      file_uidisonline_proto_msgTypes,
	}.Build()
	File_uidisonline_proto = out.File
	file_uidisonline_proto_rawDesc = nil
	file_uidisonline_proto_goTypes = nil
	file_uidisonline_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UidIsOnlineClient is the client API for UidIsOnline service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UidIsOnlineClient interface {
	UidIsOnline(ctx context.Context, in *UidIsOnlineRequest, opts ...grpc.CallOption) (*UidIsOnlineResponse, error)
}

type uidIsOnlineClient struct {
	cc grpc.ClientConnInterface
}

func NewUidIsOnlineClient(cc grpc.ClientConnInterface) UidIsOnlineClient {
	return &uidIsOnlineClient{cc}
}

func (c *uidIsOnlineClient) UidIsOnline(ctx context.Context, in *UidIsOnlineRequest, opts ...grpc.CallOption) (*UidIsOnlineResponse, error) {
	out := new(UidIsOnlineResponse)
	err := c.cc.Invoke(ctx, "/proto.UidIsOnline/UidIsOnline", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UidIsOnlineServer is the server API for UidIsOnline service.
type UidIsOnlineServer interface {
	UidIsOnline(context.Context, *UidIsOnlineRequest) (*UidIsOnlineResponse, error)
}

// UnimplementedUidIsOnlineServer can be embedded to have forward compatible implementations.
type UnimplementedUidIsOnlineServer struct {
}

func (*UnimplementedUidIsOnlineServer) UidIsOnline(context.Context, *UidIsOnlineRequest) (*UidIsOnlineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UidIsOnline not implemented")
}

func RegisterUidIsOnlineServer(s *grpc.Server, srv UidIsOnlineServer) {
	s.RegisterService(&_UidIsOnline_serviceDesc, srv)
}

func _UidIsOnline_UidIsOnline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UidIsOnlineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UidIsOnlineServer).UidIsOnline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UidIsOnline/UidIsOnline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UidIsOnlineServer).UidIsOnline(ctx, req.(*UidIsOnlineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UidIsOnline_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.UidIsOnline",
	HandlerType: (*UidIsOnlineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UidIsOnline",
			Handler:    _UidIsOnline_UidIsOnline_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "uidisonline.proto",
}
