// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: clientbinduid.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientBindUidRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Clientid string `protobuf:"bytes,1,opt,name=clientid,proto3" json:"clientid,omitempty"`
	Uid      string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *ClientBindUidRequest) Reset() {
	*x = ClientBindUidRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientbinduid_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientBindUidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientBindUidRequest) ProtoMessage() {}

func (x *ClientBindUidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clientbinduid_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientBindUidRequest.ProtoReflect.Descriptor instead.
func (*ClientBindUidRequest) Descriptor() ([]byte, []int) {
	return file_clientbinduid_proto_rawDescGZIP(), []int{0}
}

func (x *ClientBindUidRequest) GetClientid() string {
	if x != nil {
		return x.Clientid
	}
	return ""
}

func (x *ClientBindUidRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type ClientBindUidResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ClientBindUidResponse) Reset() {
	*x = ClientBindUidResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientbinduid_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientBindUidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientBindUidResponse) ProtoMessage() {}

func (x *ClientBindUidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clientbinduid_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientBindUidResponse.ProtoReflect.Descriptor instead.
func (*ClientBindUidResponse) Descriptor() ([]byte, []int) {
	return file_clientbinduid_proto_rawDescGZIP(), []int{1}
}

func (x *ClientBindUidResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

var File_clientbinduid_proto protoreflect.FileDescriptor

var file_clientbinduid_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x62, 0x69, 0x6e, 0x64, 0x75, 0x69, 0x64, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x44, 0x0a, 0x14,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x42, 0x69, 0x6e, 0x64, 0x55, 0x69, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x69, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x22, 0x2f, 0x0a, 0x15, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x42, 0x69, 0x6e, 0x64,
	0x55, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x32, 0x5d, 0x0a, 0x0d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x42, 0x69, 0x6e,
	0x64, 0x55, 0x69, 0x64, 0x12, 0x4c, 0x0a, 0x0d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x42, 0x69,
	0x6e, 0x64, 0x55, 0x69, 0x64, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x42, 0x69, 0x6e, 0x64, 0x55, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x42, 0x69, 0x6e, 0x64, 0x55, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_clientbinduid_proto_rawDescOnce sync.Once
	file_clientbinduid_proto_rawDescData = file_clientbinduid_proto_rawDesc
)

func file_clientbinduid_proto_rawDescGZIP() []byte {
	file_clientbinduid_proto_rawDescOnce.Do(func() {
		file_clientbinduid_proto_rawDescData = protoimpl.X.CompressGZIP(file_clientbinduid_proto_rawDescData)
	})
	return file_clientbinduid_proto_rawDescData
}

var file_clientbinduid_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_clientbinduid_proto_goTypes = []interface{}{
	(*ClientBindUidRequest)(nil),  // 0: proto.ClientBindUidRequest
	(*ClientBindUidResponse)(nil), // 1: proto.ClientBindUidResponse
}
var file_clientbinduid_proto_depIdxs = []int32{
	0, // 0: proto.ClientBindUid.ClientBindUid:input_type -> proto.ClientBindUidRequest
	1, // 1: proto.ClientBindUid.ClientBindUid:output_type -> proto.ClientBindUidResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_clientbinduid_proto_init() }
func file_clientbinduid_proto_init() {
	if File_clientbinduid_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_clientbinduid_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientBindUidRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientbinduid_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientBindUidResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_clientbinduid_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clientbinduid_proto_goTypes,
		DependencyIndexes: file_clientbinduid_proto_depIdxs,
		MessageInfos:      file_clientbinduid_proto_msgTypes,
	}.Build()
	File_clientbinduid_proto = out.File
	file_clientbinduid_proto_rawDesc = nil
	file_clientbinduid_proto_goTypes = nil
	file_clientbinduid_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ClientBindUidClient is the client API for ClientBindUid service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClientBindUidClient interface {
	ClientBindUid(ctx context.Context, in *ClientBindUidRequest, opts ...grpc.CallOption) (*ClientBindUidResponse, error)
}

type clientBindUidClient struct {
	cc grpc.ClientConnInterface
}

func NewClientBindUidClient(cc grpc.ClientConnInterface) ClientBindUidClient {
	return &clientBindUidClient{cc}
}

func (c *clientBindUidClient) ClientBindUid(ctx context.Context, in *ClientBindUidRequest, opts ...grpc.CallOption) (*ClientBindUidResponse, error) {
	out := new(ClientBindUidResponse)
	err := c.cc.Invoke(ctx, "/proto.ClientBindUid/ClientBindUid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientBindUidServer is the server API for ClientBindUid service.
type ClientBindUidServer interface {
	ClientBindUid(context.Context, *ClientBindUidRequest) (*ClientBindUidResponse, error)
}

// UnimplementedClientBindUidServer can be embedded to have forward compatible implementations.
type UnimplementedClientBindUidServer struct {
}

func (*UnimplementedClientBindUidServer) ClientBindUid(context.Context, *ClientBindUidRequest) (*ClientBindUidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClientBindUid not implemented")
}

func RegisterClientBindUidServer(s *grpc.Server, srv ClientBindUidServer) {
	s.RegisterService(&_ClientBindUid_serviceDesc, srv)
}

func _ClientBindUid_ClientBindUid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientBindUidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientBindUidServer).ClientBindUid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ClientBindUid/ClientBindUid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientBindUidServer).ClientBindUid(ctx, req.(*ClientBindUidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ClientBindUid_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ClientBindUid",
	HandlerType: (*ClientBindUidServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClientBindUid",
			Handler:    _ClientBindUid_ClientBindUid_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clientbinduid.proto",
}
