// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: getuidbyclient.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUidByClientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *GetUidByClientRequest) Reset() {
	*x = GetUidByClientRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_getuidbyclient_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUidByClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUidByClientRequest) ProtoMessage() {}

func (x *GetUidByClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_getuidbyclient_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUidByClientRequest.ProtoReflect.Descriptor instead.
func (*GetUidByClientRequest) Descriptor() ([]byte, []int) {
	return file_getuidbyclient_proto_rawDescGZIP(), []int{0}
}

func (x *GetUidByClientRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type GetUidByClientResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Clientid []string `protobuf:"bytes,1,rep,name=clientid,proto3" json:"clientid,omitempty"`
}

func (x *GetUidByClientResponse) Reset() {
	*x = GetUidByClientResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_getuidbyclient_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUidByClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUidByClientResponse) ProtoMessage() {}

func (x *GetUidByClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_getuidbyclient_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUidByClientResponse.ProtoReflect.Descriptor instead.
func (*GetUidByClientResponse) Descriptor() ([]byte, []int) {
	return file_getuidbyclient_proto_rawDescGZIP(), []int{1}
}

func (x *GetUidByClientResponse) GetClientid() []string {
	if x != nil {
		return x.Clientid
	}
	return nil
}

var File_getuidbyclient_proto protoreflect.FileDescriptor

var file_getuidbyclient_proto_rawDesc = []byte{
	0x0a, 0x14, 0x67, 0x65, 0x74, 0x75, 0x69, 0x64, 0x62, 0x79, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x29, 0x0a,
	0x15, 0x47, 0x65, 0x74, 0x55, 0x69, 0x64, 0x42, 0x79, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x34, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x55,
	0x69, 0x64, 0x42, 0x79, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x69, 0x64, 0x32, 0x61,
	0x0a, 0x0e, 0x47, 0x65, 0x74, 0x55, 0x69, 0x64, 0x42, 0x79, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x12, 0x4f, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x55, 0x69, 0x64, 0x42, 0x79, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x69,
	0x64, 0x42, 0x79, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x69, 0x64, 0x42,
	0x79, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_getuidbyclient_proto_rawDescOnce sync.Once
	file_getuidbyclient_proto_rawDescData = file_getuidbyclient_proto_rawDesc
)

func file_getuidbyclient_proto_rawDescGZIP() []byte {
	file_getuidbyclient_proto_rawDescOnce.Do(func() {
		file_getuidbyclient_proto_rawDescData = protoimpl.X.CompressGZIP(file_getuidbyclient_proto_rawDescData)
	})
	return file_getuidbyclient_proto_rawDescData
}

var file_getuidbyclient_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_getuidbyclient_proto_goTypes = []interface{}{
	(*GetUidByClientRequest)(nil),  // 0: proto.GetUidByClientRequest
	(*GetUidByClientResponse)(nil), // 1: proto.GetUidByClientResponse
}
var file_getuidbyclient_proto_depIdxs = []int32{
	0, // 0: proto.GetUidByClient.GetUidByClient:input_type -> proto.GetUidByClientRequest
	1, // 1: proto.GetUidByClient.GetUidByClient:output_type -> proto.GetUidByClientResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_getuidbyclient_proto_init() }
func file_getuidbyclient_proto_init() {
	if File_getuidbyclient_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_getuidbyclient_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUidByClientRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_getuidbyclient_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUidByClientResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_getuidbyclient_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_getuidbyclient_proto_goTypes,
		DependencyIndexes: file_getuidbyclient_proto_depIdxs,
		MessageInfos:      file_getuidbyclient_proto_msgTypes,
	}.Build()
	File_getuidbyclient_proto = out.File
	file_getuidbyclient_proto_rawDesc = nil
	file_getuidbyclient_proto_goTypes = nil
	file_getuidbyclient_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GetUidByClientClient is the client API for GetUidByClient service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GetUidByClientClient interface {
	GetUidByClient(ctx context.Context, in *GetUidByClientRequest, opts ...grpc.CallOption) (*GetUidByClientResponse, error)
}

type getUidByClientClient struct {
	cc grpc.ClientConnInterface
}

func NewGetUidByClientClient(cc grpc.ClientConnInterface) GetUidByClientClient {
	return &getUidByClientClient{cc}
}

func (c *getUidByClientClient) GetUidByClient(ctx context.Context, in *GetUidByClientRequest, opts ...grpc.CallOption) (*GetUidByClientResponse, error) {
	out := new(GetUidByClientResponse)
	err := c.cc.Invoke(ctx, "/proto.GetUidByClient/GetUidByClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetUidByClientServer is the server API for GetUidByClient service.
type GetUidByClientServer interface {
	GetUidByClient(context.Context, *GetUidByClientRequest) (*GetUidByClientResponse, error)
}

// UnimplementedGetUidByClientServer can be embedded to have forward compatible implementations.
type UnimplementedGetUidByClientServer struct {
}

func (*UnimplementedGetUidByClientServer) GetUidByClient(context.Context, *GetUidByClientRequest) (*GetUidByClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUidByClient not implemented")
}

func RegisterGetUidByClientServer(s *grpc.Server, srv GetUidByClientServer) {
	s.RegisterService(&_GetUidByClient_serviceDesc, srv)
}

func _GetUidByClient_GetUidByClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUidByClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetUidByClientServer).GetUidByClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GetUidByClient/GetUidByClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetUidByClientServer).GetUidByClient(ctx, req.(*GetUidByClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GetUidByClient_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GetUidByClient",
	HandlerType: (*GetUidByClientServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUidByClient",
			Handler:    _GetUidByClient_GetUidByClient_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "getuidbyclient.proto",
}
