// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: countonlineuid.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CountOnlineUidRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CountOnlineUidRequest) Reset() {
	*x = CountOnlineUidRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_countonlineuid_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountOnlineUidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountOnlineUidRequest) ProtoMessage() {}

func (x *CountOnlineUidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_countonlineuid_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountOnlineUidRequest.ProtoReflect.Descriptor instead.
func (*CountOnlineUidRequest) Descriptor() ([]byte, []int) {
	return file_countonlineuid_proto_rawDescGZIP(), []int{0}
}

type CountOnlineUidResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *CountOnlineUidResponse) Reset() {
	*x = CountOnlineUidResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_countonlineuid_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountOnlineUidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountOnlineUidResponse) ProtoMessage() {}

func (x *CountOnlineUidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_countonlineuid_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountOnlineUidResponse.ProtoReflect.Descriptor instead.
func (*CountOnlineUidResponse) Descriptor() ([]byte, []int) {
	return file_countonlineuid_proto_rawDescGZIP(), []int{1}
}

func (x *CountOnlineUidResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_countonlineuid_proto protoreflect.FileDescriptor

var file_countonlineuid_proto_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x75, 0x69, 0x64,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x17, 0x0a,
	0x15, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x55, 0x69, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2e, 0x0a, 0x16, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4f,
	0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x55, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0x61, 0x0a, 0x0e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4f,
	0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x55, 0x69, 0x64, 0x12, 0x4f, 0x0a, 0x0e, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x55, 0x69, 0x64, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x55, 0x69,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x55, 0x69, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_countonlineuid_proto_rawDescOnce sync.Once
	file_countonlineuid_proto_rawDescData = file_countonlineuid_proto_rawDesc
)

func file_countonlineuid_proto_rawDescGZIP() []byte {
	file_countonlineuid_proto_rawDescOnce.Do(func() {
		file_countonlineuid_proto_rawDescData = protoimpl.X.CompressGZIP(file_countonlineuid_proto_rawDescData)
	})
	return file_countonlineuid_proto_rawDescData
}

var file_countonlineuid_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_countonlineuid_proto_goTypes = []interface{}{
	(*CountOnlineUidRequest)(nil),  // 0: proto.CountOnlineUidRequest
	(*CountOnlineUidResponse)(nil), // 1: proto.CountOnlineUidResponse
}
var file_countonlineuid_proto_depIdxs = []int32{
	0, // 0: proto.CountOnlineUid.CountOnlineUid:input_type -> proto.CountOnlineUidRequest
	1, // 1: proto.CountOnlineUid.CountOnlineUid:output_type -> proto.CountOnlineUidResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_countonlineuid_proto_init() }
func file_countonlineuid_proto_init() {
	if File_countonlineuid_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_countonlineuid_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountOnlineUidRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_countonlineuid_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountOnlineUidResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_countonlineuid_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_countonlineuid_proto_goTypes,
		DependencyIndexes: file_countonlineuid_proto_depIdxs,
		MessageInfos:      file_countonlineuid_proto_msgTypes,
	}.Build()
	File_countonlineuid_proto = out.File
	file_countonlineuid_proto_rawDesc = nil
	file_countonlineuid_proto_goTypes = nil
	file_countonlineuid_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CountOnlineUidClient is the client API for CountOnlineUid service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CountOnlineUidClient interface {
	CountOnlineUid(ctx context.Context, in *CountOnlineUidRequest, opts ...grpc.CallOption) (*CountOnlineUidResponse, error)
}

type countOnlineUidClient struct {
	cc grpc.ClientConnInterface
}

func NewCountOnlineUidClient(cc grpc.ClientConnInterface) CountOnlineUidClient {
	return &countOnlineUidClient{cc}
}

func (c *countOnlineUidClient) CountOnlineUid(ctx context.Context, in *CountOnlineUidRequest, opts ...grpc.CallOption) (*CountOnlineUidResponse, error) {
	out := new(CountOnlineUidResponse)
	err := c.cc.Invoke(ctx, "/proto.CountOnlineUid/CountOnlineUid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CountOnlineUidServer is the server API for CountOnlineUid service.
type CountOnlineUidServer interface {
	CountOnlineUid(context.Context, *CountOnlineUidRequest) (*CountOnlineUidResponse, error)
}

// UnimplementedCountOnlineUidServer can be embedded to have forward compatible implementations.
type UnimplementedCountOnlineUidServer struct {
}

func (*UnimplementedCountOnlineUidServer) CountOnlineUid(context.Context, *CountOnlineUidRequest) (*CountOnlineUidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CountOnlineUid not implemented")
}

func RegisterCountOnlineUidServer(s *grpc.Server, srv CountOnlineUidServer) {
	s.RegisterService(&_CountOnlineUid_serviceDesc, srv)
}

func _CountOnlineUid_CountOnlineUid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountOnlineUidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CountOnlineUidServer).CountOnlineUid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CountOnlineUid/CountOnlineUid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CountOnlineUidServer).CountOnlineUid(ctx, req.(*CountOnlineUidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CountOnlineUid_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CountOnlineUid",
	HandlerType: (*CountOnlineUidServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CountOnlineUid",
			Handler:    _CountOnlineUid_CountOnlineUid_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "countonlineuid.proto",
}
