// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: clonseclient.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClonseClientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Clientid string `protobuf:"bytes,1,opt,name=clientid,proto3" json:"clientid,omitempty"`
}

func (x *ClonseClientRequest) Reset() {
	*x = ClonseClientRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clonseclient_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClonseClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClonseClientRequest) ProtoMessage() {}

func (x *ClonseClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clonseclient_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClonseClientRequest.ProtoReflect.Descriptor instead.
func (*ClonseClientRequest) Descriptor() ([]byte, []int) {
	return file_clonseclient_proto_rawDescGZIP(), []int{0}
}

func (x *ClonseClientRequest) GetClientid() string {
	if x != nil {
		return x.Clientid
	}
	return ""
}

type ClonseClientResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ClonseClientResponse) Reset() {
	*x = ClonseClientResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clonseclient_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClonseClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClonseClientResponse) ProtoMessage() {}

func (x *ClonseClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clonseclient_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClonseClientResponse.ProtoReflect.Descriptor instead.
func (*ClonseClientResponse) Descriptor() ([]byte, []int) {
	return file_clonseclient_proto_rawDescGZIP(), []int{1}
}

func (x *ClonseClientResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

var File_clonseclient_proto protoreflect.FileDescriptor

var file_clonseclient_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x6c, 0x6f, 0x6e, 0x73, 0x65, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x31, 0x0a, 0x13, 0x43,
	0x6c, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x69, 0x64, 0x22, 0x2e,
	0x0a, 0x14, 0x43, 0x6c, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x59,
	0x0a, 0x0c, 0x43, 0x6c, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x49,
	0x0a, 0x0c, 0x43, 0x6c, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x1a,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_clonseclient_proto_rawDescOnce sync.Once
	file_clonseclient_proto_rawDescData = file_clonseclient_proto_rawDesc
)

func file_clonseclient_proto_rawDescGZIP() []byte {
	file_clonseclient_proto_rawDescOnce.Do(func() {
		file_clonseclient_proto_rawDescData = protoimpl.X.CompressGZIP(file_clonseclient_proto_rawDescData)
	})
	return file_clonseclient_proto_rawDescData
}

var file_clonseclient_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_clonseclient_proto_goTypes = []interface{}{
	(*ClonseClientRequest)(nil),  // 0: proto.ClonseClientRequest
	(*ClonseClientResponse)(nil), // 1: proto.ClonseClientResponse
}
var file_clonseclient_proto_depIdxs = []int32{
	0, // 0: proto.ClonseClient.ClonseClient:input_type -> proto.ClonseClientRequest
	1, // 1: proto.ClonseClient.ClonseClient:output_type -> proto.ClonseClientResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_clonseclient_proto_init() }
func file_clonseclient_proto_init() {
	if File_clonseclient_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_clonseclient_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClonseClientRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clonseclient_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClonseClientResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_clonseclient_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clonseclient_proto_goTypes,
		DependencyIndexes: file_clonseclient_proto_depIdxs,
		MessageInfos:      file_clonseclient_proto_msgTypes,
	}.Build()
	File_clonseclient_proto = out.File
	file_clonseclient_proto_rawDesc = nil
	file_clonseclient_proto_goTypes = nil
	file_clonseclient_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ClonseClientClient is the client API for ClonseClient service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClonseClientClient interface {
	ClonseClient(ctx context.Context, in *ClonseClientRequest, opts ...grpc.CallOption) (*ClonseClientResponse, error)
}

type clonseClientClient struct {
	cc grpc.ClientConnInterface
}

func NewClonseClientClient(cc grpc.ClientConnInterface) ClonseClientClient {
	return &clonseClientClient{cc}
}

func (c *clonseClientClient) ClonseClient(ctx context.Context, in *ClonseClientRequest, opts ...grpc.CallOption) (*ClonseClientResponse, error) {
	out := new(ClonseClientResponse)
	err := c.cc.Invoke(ctx, "/proto.ClonseClient/ClonseClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClonseClientServer is the server API for ClonseClient service.
type ClonseClientServer interface {
	ClonseClient(context.Context, *ClonseClientRequest) (*ClonseClientResponse, error)
}

// UnimplementedClonseClientServer can be embedded to have forward compatible implementations.
type UnimplementedClonseClientServer struct {
}

func (*UnimplementedClonseClientServer) ClonseClient(context.Context, *ClonseClientRequest) (*ClonseClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClonseClient not implemented")
}

func RegisterClonseClientServer(s *grpc.Server, srv ClonseClientServer) {
	s.RegisterService(&_ClonseClient_serviceDesc, srv)
}

func _ClonseClient_ClonseClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClonseClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClonseClientServer).ClonseClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ClonseClient/ClonseClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClonseClientServer).ClonseClient(ctx, req.(*ClonseClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ClonseClient_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ClonseClient",
	HandlerType: (*ClonseClientServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClonseClient",
			Handler:    _ClonseClient_ClonseClient_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clonseclient.proto",
}
