// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: sendmessagetouid.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendMessageToUidRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid     string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SendMessageToUidRequest) Reset() {
	*x = SendMessageToUidRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sendmessagetouid_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMessageToUidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageToUidRequest) ProtoMessage() {}

func (x *SendMessageToUidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sendmessagetouid_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageToUidRequest.ProtoReflect.Descriptor instead.
func (*SendMessageToUidRequest) Descriptor() ([]byte, []int) {
	return file_sendmessagetouid_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessageToUidRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *SendMessageToUidRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SendMessageToUidResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *SendMessageToUidResponse) Reset() {
	*x = SendMessageToUidResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sendmessagetouid_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMessageToUidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageToUidResponse) ProtoMessage() {}

func (x *SendMessageToUidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sendmessagetouid_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageToUidResponse.ProtoReflect.Descriptor instead.
func (*SendMessageToUidResponse) Descriptor() ([]byte, []int) {
	return file_sendmessagetouid_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageToUidResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

var File_sendmessagetouid_proto protoreflect.FileDescriptor

var file_sendmessagetouid_proto_rawDesc = []byte{
	0x0a, 0x16, 0x73, 0x65, 0x6e, 0x64, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x74, 0x6f, 0x75,
	0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x45, 0x0a, 0x17, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x6f,
	0x55, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x32, 0x0a, 0x18, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x55, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x69, 0x0a, 0x10, 0x53, 0x65,
	0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x55, 0x69, 0x64, 0x12, 0x55,
	0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x55,
	0x69, 0x64, 0x12, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x55, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x55, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sendmessagetouid_proto_rawDescOnce sync.Once
	file_sendmessagetouid_proto_rawDescData = file_sendmessagetouid_proto_rawDesc
)

func file_sendmessagetouid_proto_rawDescGZIP() []byte {
	file_sendmessagetouid_proto_rawDescOnce.Do(func() {
		file_sendmessagetouid_proto_rawDescData = protoimpl.X.CompressGZIP(file_sendmessagetouid_proto_rawDescData)
	})
	return file_sendmessagetouid_proto_rawDescData
}

var file_sendmessagetouid_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sendmessagetouid_proto_goTypes = []interface{}{
	(*SendMessageToUidRequest)(nil),  // 0: proto.SendMessageToUidRequest
	(*SendMessageToUidResponse)(nil), // 1: proto.SendMessageToUidResponse
}
var file_sendmessagetouid_proto_depIdxs = []int32{
	0, // 0: proto.SendMessageToUid.SendMessageToUid:input_type -> proto.SendMessageToUidRequest
	1, // 1: proto.SendMessageToUid.SendMessageToUid:output_type -> proto.SendMessageToUidResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sendmessagetouid_proto_init() }
func file_sendmessagetouid_proto_init() {
	if File_sendmessagetouid_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sendmessagetouid_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMessageToUidRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sendmessagetouid_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMessageToUidResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sendmessagetouid_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sendmessagetouid_proto_goTypes,
		DependencyIndexes: file_sendmessagetouid_proto_depIdxs,
		MessageInfos:      file_sendmessagetouid_proto_msgTypes,
	}.Build()
	File_sendmessagetouid_proto = out.File
	file_sendmessagetouid_proto_rawDesc = nil
	file_sendmessagetouid_proto_goTypes = nil
	file_sendmessagetouid_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SendMessageToUidClient is the client API for SendMessageToUid service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SendMessageToUidClient interface {
	SendMessageToUid(ctx context.Context, in *SendMessageToUidRequest, opts ...grpc.CallOption) (*SendMessageToUidResponse, error)
}

type sendMessageToUidClient struct {
	cc grpc.ClientConnInterface
}

func NewSendMessageToUidClient(cc grpc.ClientConnInterface) SendMessageToUidClient {
	return &sendMessageToUidClient{cc}
}

func (c *sendMessageToUidClient) SendMessageToUid(ctx context.Context, in *SendMessageToUidRequest, opts ...grpc.CallOption) (*SendMessageToUidResponse, error) {
	out := new(SendMessageToUidResponse)
	err := c.cc.Invoke(ctx, "/proto.SendMessageToUid/SendMessageToUid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SendMessageToUidServer is the server API for SendMessageToUid service.
type SendMessageToUidServer interface {
	SendMessageToUid(context.Context, *SendMessageToUidRequest) (*SendMessageToUidResponse, error)
}

// UnimplementedSendMessageToUidServer can be embedded to have forward compatible implementations.
type UnimplementedSendMessageToUidServer struct {
}

func (*UnimplementedSendMessageToUidServer) SendMessageToUid(context.Context, *SendMessageToUidRequest) (*SendMessageToUidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessageToUid not implemented")
}

func RegisterSendMessageToUidServer(s *grpc.Server, srv SendMessageToUidServer) {
	s.RegisterService(&_SendMessageToUid_serviceDesc, srv)
}

func _SendMessageToUid_SendMessageToUid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageToUidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendMessageToUidServer).SendMessageToUid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SendMessageToUid/SendMessageToUid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendMessageToUidServer).SendMessageToUid(ctx, req.(*SendMessageToUidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SendMessageToUid_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SendMessageToUid",
	HandlerType: (*SendMessageToUidServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessageToUid",
			Handler:    _SendMessageToUid_SendMessageToUid_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sendmessagetouid.proto",
}
