// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: countonlinegroup.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CountOnlineGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
}

func (x *CountOnlineGroupRequest) Reset() {
	*x = CountOnlineGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_countonlinegroup_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountOnlineGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountOnlineGroupRequest) ProtoMessage() {}

func (x *CountOnlineGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_countonlinegroup_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountOnlineGroupRequest.ProtoReflect.Descriptor instead.
func (*CountOnlineGroupRequest) Descriptor() ([]byte, []int) {
	return file_countonlinegroup_proto_rawDescGZIP(), []int{0}
}

func (x *CountOnlineGroupRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type CountOnlineGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *CountOnlineGroupResponse) Reset() {
	*x = CountOnlineGroupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_countonlinegroup_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountOnlineGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountOnlineGroupResponse) ProtoMessage() {}

func (x *CountOnlineGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_countonlinegroup_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountOnlineGroupResponse.ProtoReflect.Descriptor instead.
func (*CountOnlineGroupResponse) Descriptor() ([]byte, []int) {
	return file_countonlinegroup_proto_rawDescGZIP(), []int{1}
}

func (x *CountOnlineGroupResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_countonlinegroup_proto protoreflect.FileDescriptor

var file_countonlinegroup_proto_rawDesc = []byte{
	0x0a, 0x16, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x2f, 0x0a, 0x17, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x22, 0x30, 0x0a, 0x18, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x32, 0x69, 0x0a, 0x10, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4f, 0x6e, 0x6c, 0x69, 0x6e,
	0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x55, 0x0a, 0x10, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4f,
	0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x1e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0a, 0x5a,
	0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_countonlinegroup_proto_rawDescOnce sync.Once
	file_countonlinegroup_proto_rawDescData = file_countonlinegroup_proto_rawDesc
)

func file_countonlinegroup_proto_rawDescGZIP() []byte {
	file_countonlinegroup_proto_rawDescOnce.Do(func() {
		file_countonlinegroup_proto_rawDescData = protoimpl.X.CompressGZIP(file_countonlinegroup_proto_rawDescData)
	})
	return file_countonlinegroup_proto_rawDescData
}

var file_countonlinegroup_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_countonlinegroup_proto_goTypes = []interface{}{
	(*CountOnlineGroupRequest)(nil),  // 0: proto.CountOnlineGroupRequest
	(*CountOnlineGroupResponse)(nil), // 1: proto.CountOnlineGroupResponse
}
var file_countonlinegroup_proto_depIdxs = []int32{
	0, // 0: proto.CountOnlineGroup.CountOnlineGroup:input_type -> proto.CountOnlineGroupRequest
	1, // 1: proto.CountOnlineGroup.CountOnlineGroup:output_type -> proto.CountOnlineGroupResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_countonlinegroup_proto_init() }
func file_countonlinegroup_proto_init() {
	if File_countonlinegroup_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_countonlinegroup_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountOnlineGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_countonlinegroup_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountOnlineGroupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_countonlinegroup_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_countonlinegroup_proto_goTypes,
		DependencyIndexes: file_countonlinegroup_proto_depIdxs,
		MessageInfos:      file_countonlinegroup_proto_msgTypes,
	}.Build()
	File_countonlinegroup_proto = out.File
	file_countonlinegroup_proto_rawDesc = nil
	file_countonlinegroup_proto_goTypes = nil
	file_countonlinegroup_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CountOnlineGroupClient is the client API for CountOnlineGroup service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CountOnlineGroupClient interface {
	CountOnlineGroup(ctx context.Context, in *CountOnlineGroupRequest, opts ...grpc.CallOption) (*CountOnlineGroupResponse, error)
}

type countOnlineGroupClient struct {
	cc grpc.ClientConnInterface
}

func NewCountOnlineGroupClient(cc grpc.ClientConnInterface) CountOnlineGroupClient {
	return &countOnlineGroupClient{cc}
}

func (c *countOnlineGroupClient) CountOnlineGroup(ctx context.Context, in *CountOnlineGroupRequest, opts ...grpc.CallOption) (*CountOnlineGroupResponse, error) {
	out := new(CountOnlineGroupResponse)
	err := c.cc.Invoke(ctx, "/proto.CountOnlineGroup/CountOnlineGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CountOnlineGroupServer is the server API for CountOnlineGroup service.
type CountOnlineGroupServer interface {
	CountOnlineGroup(context.Context, *CountOnlineGroupRequest) (*CountOnlineGroupResponse, error)
}

// UnimplementedCountOnlineGroupServer can be embedded to have forward compatible implementations.
type UnimplementedCountOnlineGroupServer struct {
}

func (*UnimplementedCountOnlineGroupServer) CountOnlineGroup(context.Context, *CountOnlineGroupRequest) (*CountOnlineGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CountOnlineGroup not implemented")
}

func RegisterCountOnlineGroupServer(s *grpc.Server, srv CountOnlineGroupServer) {
	s.RegisterService(&_CountOnlineGroup_serviceDesc, srv)
}

func _CountOnlineGroup_CountOnlineGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountOnlineGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CountOnlineGroupServer).CountOnlineGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CountOnlineGroup/CountOnlineGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CountOnlineGroupServer).CountOnlineGroup(ctx, req.(*CountOnlineGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CountOnlineGroup_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CountOnlineGroup",
	HandlerType: (*CountOnlineGroupServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CountOnlineGroup",
			Handler:    _CountOnlineGroup_CountOnlineGroup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "countonlinegroup.proto",
}
