// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: unbinduid.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnBindUidRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Clientid string `protobuf:"bytes,1,opt,name=clientid,proto3" json:"clientid,omitempty"`
}

func (x *UnBindUidRequest) Reset() {
	*x = UnBindUidRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unbinduid_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnBindUidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnBindUidRequest) ProtoMessage() {}

func (x *UnBindUidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_unbinduid_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnBindUidRequest.ProtoReflect.Descriptor instead.
func (*UnBindUidRequest) Descriptor() ([]byte, []int) {
	return file_unbinduid_proto_rawDescGZIP(), []int{0}
}

func (x *UnBindUidRequest) GetClientid() string {
	if x != nil {
		return x.Clientid
	}
	return ""
}

type UnBindUidResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *UnBindUidResponse) Reset() {
	*x = UnBindUidResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unbinduid_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnBindUidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnBindUidResponse) ProtoMessage() {}

func (x *UnBindUidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_unbinduid_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnBindUidResponse.ProtoReflect.Descriptor instead.
func (*UnBindUidResponse) Descriptor() ([]byte, []int) {
	return file_unbinduid_proto_rawDescGZIP(), []int{1}
}

func (x *UnBindUidResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

var File_unbinduid_proto protoreflect.FileDescriptor

var file_unbinduid_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x75, 0x6e, 0x62, 0x69, 0x6e, 0x64, 0x75, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2e, 0x0a, 0x10, 0x55, 0x6e, 0x42, 0x69,
	0x6e, 0x64, 0x55, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x69, 0x64, 0x22, 0x2b, 0x0a, 0x11, 0x55, 0x6e, 0x42, 0x69,
	0x6e, 0x64, 0x55, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x4d, 0x0a, 0x09, 0x55, 0x6e, 0x42, 0x69, 0x6e, 0x64, 0x55,
	0x69, 0x64, 0x12, 0x40, 0x0a, 0x09, 0x55, 0x6e, 0x42, 0x69, 0x6e, 0x64, 0x55, 0x69, 0x64, 0x12,
	0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x6e, 0x42, 0x69, 0x6e, 0x64, 0x55, 0x69,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x55, 0x6e, 0x42, 0x69, 0x6e, 0x64, 0x55, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_unbinduid_proto_rawDescOnce sync.Once
	file_unbinduid_proto_rawDescData = file_unbinduid_proto_rawDesc
)

func file_unbinduid_proto_rawDescGZIP() []byte {
	file_unbinduid_proto_rawDescOnce.Do(func() {
		file_unbinduid_proto_rawDescData = protoimpl.X.CompressGZIP(file_unbinduid_proto_rawDescData)
	})
	return file_unbinduid_proto_rawDescData
}

var file_unbinduid_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_unbinduid_proto_goTypes = []interface{}{
	(*UnBindUidRequest)(nil),  // 0: proto.UnBindUidRequest
	(*UnBindUidResponse)(nil), // 1: proto.UnBindUidResponse
}
var file_unbinduid_proto_depIdxs = []int32{
	0, // 0: proto.UnBindUid.UnBindUid:input_type -> proto.UnBindUidRequest
	1, // 1: proto.UnBindUid.UnBindUid:output_type -> proto.UnBindUidResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_unbinduid_proto_init() }
func file_unbinduid_proto_init() {
	if File_unbinduid_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_unbinduid_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnBindUidRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unbinduid_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnBindUidResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_unbinduid_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_unbinduid_proto_goTypes,
		DependencyIndexes: file_unbinduid_proto_depIdxs,
		MessageInfos:      file_unbinduid_proto_msgTypes,
	}.Build()
	File_unbinduid_proto = out.File
	file_unbinduid_proto_rawDesc = nil
	file_unbinduid_proto_goTypes = nil
	file_unbinduid_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UnBindUidClient is the client API for UnBindUid service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UnBindUidClient interface {
	UnBindUid(ctx context.Context, in *UnBindUidRequest, opts ...grpc.CallOption) (*UnBindUidResponse, error)
}

type unBindUidClient struct {
	cc grpc.ClientConnInterface
}

func NewUnBindUidClient(cc grpc.ClientConnInterface) UnBindUidClient {
	return &unBindUidClient{cc}
}

func (c *unBindUidClient) UnBindUid(ctx context.Context, in *UnBindUidRequest, opts ...grpc.CallOption) (*UnBindUidResponse, error) {
	out := new(UnBindUidResponse)
	err := c.cc.Invoke(ctx, "/proto.UnBindUid/UnBindUid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UnBindUidServer is the server API for UnBindUid service.
type UnBindUidServer interface {
	UnBindUid(context.Context, *UnBindUidRequest) (*UnBindUidResponse, error)
}

// UnimplementedUnBindUidServer can be embedded to have forward compatible implementations.
type UnimplementedUnBindUidServer struct {
}

func (*UnimplementedUnBindUidServer) UnBindUid(context.Context, *UnBindUidRequest) (*UnBindUidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnBindUid not implemented")
}

func RegisterUnBindUidServer(s *grpc.Server, srv UnBindUidServer) {
	s.RegisterService(&_UnBindUid_serviceDesc, srv)
}

func _UnBindUid_UnBindUid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnBindUidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnBindUidServer).UnBindUid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UnBindUid/UnBindUid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnBindUidServer).UnBindUid(ctx, req.(*UnBindUidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UnBindUid_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.UnBindUid",
	HandlerType: (*UnBindUidServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UnBindUid",
			Handler:    _UnBindUid_UnBindUid_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "unbinduid.proto",
}
