// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: clientisonline.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientIsOnlineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Clientid string `protobuf:"bytes,1,opt,name=clientid,proto3" json:"clientid,omitempty"`
}

func (x *ClientIsOnlineRequest) Reset() {
	*x = ClientIsOnlineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientisonline_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientIsOnlineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientIsOnlineRequest) ProtoMessage() {}

func (x *ClientIsOnlineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clientisonline_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientIsOnlineRequest.ProtoReflect.Descriptor instead.
func (*ClientIsOnlineRequest) Descriptor() ([]byte, []int) {
	return file_clientisonline_proto_rawDescGZIP(), []int{0}
}

func (x *ClientIsOnlineRequest) GetClientid() string {
	if x != nil {
		return x.Clientid
	}
	return ""
}

type ClientIsOnlineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Isonline bool `protobuf:"varint,1,opt,name=isonline,proto3" json:"isonline,omitempty"`
}

func (x *ClientIsOnlineResponse) Reset() {
	*x = ClientIsOnlineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientisonline_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientIsOnlineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientIsOnlineResponse) ProtoMessage() {}

func (x *ClientIsOnlineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clientisonline_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientIsOnlineResponse.ProtoReflect.Descriptor instead.
func (*ClientIsOnlineResponse) Descriptor() ([]byte, []int) {
	return file_clientisonline_proto_rawDescGZIP(), []int{1}
}

func (x *ClientIsOnlineResponse) GetIsonline() bool {
	if x != nil {
		return x.Isonline
	}
	return false
}

var File_clientisonline_proto protoreflect.FileDescriptor

var file_clientisonline_proto_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x69, 0x73, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x33, 0x0a,
	0x15, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x73, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x69, 0x64, 0x22, 0x34, 0x0a, 0x16, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x73, 0x4f, 0x6e,
	0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x69, 0x73, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08,
	0x69, 0x73, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x32, 0x61, 0x0a, 0x0e, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x49, 0x73, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x4f, 0x0a, 0x0e, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x49, 0x73, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x1c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x73, 0x4f, 0x6e, 0x6c,
	0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x73, 0x4f, 0x6e, 0x6c, 0x69, 0x6e,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e,
	0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_clientisonline_proto_rawDescOnce sync.Once
	file_clientisonline_proto_rawDescData = file_clientisonline_proto_rawDesc
)

func file_clientisonline_proto_rawDescGZIP() []byte {
	file_clientisonline_proto_rawDescOnce.Do(func() {
		file_clientisonline_proto_rawDescData = protoimpl.X.CompressGZIP(file_clientisonline_proto_rawDescData)
	})
	return file_clientisonline_proto_rawDescData
}

var file_clientisonline_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_clientisonline_proto_goTypes = []interface{}{
	(*ClientIsOnlineRequest)(nil),  // 0: proto.ClientIsOnlineRequest
	(*ClientIsOnlineResponse)(nil), // 1: proto.ClientIsOnlineResponse
}
var file_clientisonline_proto_depIdxs = []int32{
	0, // 0: proto.ClientIsOnline.ClientIsOnline:input_type -> proto.ClientIsOnlineRequest
	1, // 1: proto.ClientIsOnline.ClientIsOnline:output_type -> proto.ClientIsOnlineResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_clientisonline_proto_init() }
func file_clientisonline_proto_init() {
	if File_clientisonline_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_clientisonline_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientIsOnlineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientisonline_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientIsOnlineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_clientisonline_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clientisonline_proto_goTypes,
		DependencyIndexes: file_clientisonline_proto_depIdxs,
		MessageInfos:      file_clientisonline_proto_msgTypes,
	}.Build()
	File_clientisonline_proto = out.File
	file_clientisonline_proto_rawDesc = nil
	file_clientisonline_proto_goTypes = nil
	file_clientisonline_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ClientIsOnlineClient is the client API for ClientIsOnline service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClientIsOnlineClient interface {
	ClientIsOnline(ctx context.Context, in *ClientIsOnlineRequest, opts ...grpc.CallOption) (*ClientIsOnlineResponse, error)
}

type clientIsOnlineClient struct {
	cc grpc.ClientConnInterface
}

func NewClientIsOnlineClient(cc grpc.ClientConnInterface) ClientIsOnlineClient {
	return &clientIsOnlineClient{cc}
}

func (c *clientIsOnlineClient) ClientIsOnline(ctx context.Context, in *ClientIsOnlineRequest, opts ...grpc.CallOption) (*ClientIsOnlineResponse, error) {
	out := new(ClientIsOnlineResponse)
	err := c.cc.Invoke(ctx, "/proto.ClientIsOnline/ClientIsOnline", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientIsOnlineServer is the server API for ClientIsOnline service.
type ClientIsOnlineServer interface {
	ClientIsOnline(context.Context, *ClientIsOnlineRequest) (*ClientIsOnlineResponse, error)
}

// UnimplementedClientIsOnlineServer can be embedded to have forward compatible implementations.
type UnimplementedClientIsOnlineServer struct {
}

func (*UnimplementedClientIsOnlineServer) ClientIsOnline(context.Context, *ClientIsOnlineRequest) (*ClientIsOnlineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClientIsOnline not implemented")
}

func RegisterClientIsOnlineServer(s *grpc.Server, srv ClientIsOnlineServer) {
	s.RegisterService(&_ClientIsOnline_serviceDesc, srv)
}

func _ClientIsOnline_ClientIsOnline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientIsOnlineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientIsOnlineServer).ClientIsOnline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ClientIsOnline/ClientIsOnline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientIsOnlineServer).ClientIsOnline(ctx, req.(*ClientIsOnlineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ClientIsOnline_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ClientIsOnline",
	HandlerType: (*ClientIsOnlineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClientIsOnline",
			Handler:    _ClientIsOnline_ClientIsOnline_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clientisonline.proto",
}
