// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: getallonlineclient.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAllOnlineClientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllOnlineClientRequest) Reset() {
	*x = GetAllOnlineClientRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_getallonlineclient_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllOnlineClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllOnlineClientRequest) ProtoMessage() {}

func (x *GetAllOnlineClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_getallonlineclient_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllOnlineClientRequest.ProtoReflect.Descriptor instead.
func (*GetAllOnlineClientRequest) Descriptor() ([]byte, []int) {
	return file_getallonlineclient_proto_rawDescGZIP(), []int{0}
}

type GetAllOnlineClientResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Client []string `protobuf:"bytes,1,rep,name=client,proto3" json:"client,omitempty"`
}

func (x *GetAllOnlineClientResponse) Reset() {
	*x = GetAllOnlineClientResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_getallonlineclient_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllOnlineClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllOnlineClientResponse) ProtoMessage() {}

func (x *GetAllOnlineClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_getallonlineclient_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllOnlineClientResponse.ProtoReflect.Descriptor instead.
func (*GetAllOnlineClientResponse) Descriptor() ([]byte, []int) {
	return file_getallonlineclient_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllOnlineClientResponse) GetClient() []string {
	if x != nil {
		return x.Client
	}
	return nil
}

var File_getallonlineclient_proto protoreflect.FileDescriptor

var file_getallonlineclient_proto_rawDesc = []byte{
	0x0a, 0x18, 0x67, 0x65, 0x74, 0x61, 0x6c, 0x6c, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x1b, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4f, 0x6e, 0x6c, 0x69, 0x6e,
	0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x34,
	0x0a, 0x1a, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x32, 0x71, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4f, 0x6e,
	0x6c, 0x69, 0x6e, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x5b, 0x0a, 0x12, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x12, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4f,
	0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_getallonlineclient_proto_rawDescOnce sync.Once
	file_getallonlineclient_proto_rawDescData = file_getallonlineclient_proto_rawDesc
)

func file_getallonlineclient_proto_rawDescGZIP() []byte {
	file_getallonlineclient_proto_rawDescOnce.Do(func() {
		file_getallonlineclient_proto_rawDescData = protoimpl.X.CompressGZIP(file_getallonlineclient_proto_rawDescData)
	})
	return file_getallonlineclient_proto_rawDescData
}

var file_getallonlineclient_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_getallonlineclient_proto_goTypes = []interface{}{
	(*GetAllOnlineClientRequest)(nil),  // 0: proto.GetAllOnlineClientRequest
	(*GetAllOnlineClientResponse)(nil), // 1: proto.GetAllOnlineClientResponse
}
var file_getallonlineclient_proto_depIdxs = []int32{
	0, // 0: proto.GetAllOnlineClient.GetAllOnlineClient:input_type -> proto.GetAllOnlineClientRequest
	1, // 1: proto.GetAllOnlineClient.GetAllOnlineClient:output_type -> proto.GetAllOnlineClientResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_getallonlineclient_proto_init() }
func file_getallonlineclient_proto_init() {
	if File_getallonlineclient_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_getallonlineclient_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllOnlineClientRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_getallonlineclient_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllOnlineClientResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_getallonlineclient_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_getallonlineclient_proto_goTypes,
		DependencyIndexes: file_getallonlineclient_proto_depIdxs,
		MessageInfos:      file_getallonlineclient_proto_msgTypes,
	}.Build()
	File_getallonlineclient_proto = out.File
	file_getallonlineclient_proto_rawDesc = nil
	file_getallonlineclient_proto_goTypes = nil
	file_getallonlineclient_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GetAllOnlineClientClient is the client API for GetAllOnlineClient service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GetAllOnlineClientClient interface {
	GetAllOnlineClient(ctx context.Context, in *GetAllOnlineClientRequest, opts ...grpc.CallOption) (*GetAllOnlineClientResponse, error)
}

type getAllOnlineClientClient struct {
	cc grpc.ClientConnInterface
}

func NewGetAllOnlineClientClient(cc grpc.ClientConnInterface) GetAllOnlineClientClient {
	return &getAllOnlineClientClient{cc}
}

func (c *getAllOnlineClientClient) GetAllOnlineClient(ctx context.Context, in *GetAllOnlineClientRequest, opts ...grpc.CallOption) (*GetAllOnlineClientResponse, error) {
	out := new(GetAllOnlineClientResponse)
	err := c.cc.Invoke(ctx, "/proto.GetAllOnlineClient/GetAllOnlineClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetAllOnlineClientServer is the server API for GetAllOnlineClient service.
type GetAllOnlineClientServer interface {
	GetAllOnlineClient(context.Context, *GetAllOnlineClientRequest) (*GetAllOnlineClientResponse, error)
}

// UnimplementedGetAllOnlineClientServer can be embedded to have forward compatible implementations.
type UnimplementedGetAllOnlineClientServer struct {
}

func (*UnimplementedGetAllOnlineClientServer) GetAllOnlineClient(context.Context, *GetAllOnlineClientRequest) (*GetAllOnlineClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllOnlineClient not implemented")
}

func RegisterGetAllOnlineClientServer(s *grpc.Server, srv GetAllOnlineClientServer) {
	s.RegisterService(&_GetAllOnlineClient_serviceDesc, srv)
}

func _GetAllOnlineClient_GetAllOnlineClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllOnlineClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetAllOnlineClientServer).GetAllOnlineClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GetAllOnlineClient/GetAllOnlineClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetAllOnlineClientServer).GetAllOnlineClient(ctx, req.(*GetAllOnlineClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GetAllOnlineClient_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GetAllOnlineClient",
	HandlerType: (*GetAllOnlineClientServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllOnlineClient",
			Handler:    _GetAllOnlineClient_GetAllOnlineClient_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "getallonlineclient.proto",
}
